### ISSUE TITLE
Make it more external

### ISSUE THREAD

**Issue by CodeMaker62631** [Skwrr/Dexterion#75]
### 📝 Provide a description of the new feature

i get red trust factor really fast when on a fresh account and i only used skeleton, name esp and health nothing else so pleaes make it less red trust factor triggering somehow make it more external or somethimg

### ➕ Additional Information

12313123

**Comment by kvfs2k07** [comment]
how'd you make it "more external"?
I'm very intrigued on how to do it

Mind sharing one of your games demos check it's not a gameplay issue?
Not trying to be rude, but a cheat cannot be "more external" unless you add a kernel driver to read the game's memory (which you can add from [Kernel-Dexterion](https://github.com/Nocture-Insight/Kernel-Dexterion/)).
Also, you get Red Trust because you get reported too much.
